project:
  type: default

format:
  live-revealjs:
    theme: simple
    auto-stretch: false
    self-contained: true
    embed-resources: true
    scrollable: true
webr:
  cell-options:
    fig-width: 10
    fig-height: 6
    max-lines: 15
revealjs-plugins:
  - drop